refugee_homepage:
    path:     /
    defaults: { _controller: RefugeeBundle:Default:index }

add:
    path:     /add/{id}
    defaults: { _controller: RefugeeBundle:Refugee:add }
affiche:
    path:     /affiche
    defaults: { _controller: RefugeeBundle:Refugee:getAllRefugees }
recherche:
    path:     /recherche/{id}
    defaults: { _controller: RefugeeBundle:Refugee:getRefugee}
update:
    path:     /update/{id}
    defaults: { _controller: RefugeeBundle:Refugee:updateRefugee}
delete:
    path:     /delete/{id}
    defaults: { _controller: RefugeeBundle:Refugee:delete}
getCountRef:
    path:     /getCountRef/{location}
    defaults: { _controller: RefugeeBundle:Refugee:getCountRef}
Sum:
    path:     /sumByNeeds
    defaults: { _controller: RefugeeBundle:Refugee:sumByNeeds}

addBen:
    path:     /addBen
    defaults: { _controller: RefugeeBundle:Benevole:add }

get_all:
    path:     /getAllBen
    defaults: { _controller: RefugeeBundle:Benevole:getAll }

get_benevole:
    path:     /getBenevoleBen/{id}
    defaults: { _controller: RefugeeBundle:Benevole:getBenevole }

update_benevole:
    path:     /updateBenevole/{id}
    defaults: { _controller: RefugeeBundle:Benevole:updateBenevole }

deleteBen:
    path:     /deleteBen/{id}
    defaults: { _controller: RefugeeBundle:Benevole:delete }

getBenByVille:
    path:     /getBenLoc/{location}/{max}
    defaults: { _controller: RefugeeBundle:Benevole:getBenevoleByLoc }
