event:
    resource: "@EventBundle/Resources/config/routing.yml"
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

association:
    resource: "@AssociationBundle/Resources/config/routing.yml"

donation:
    resource: "@DonationBundle/Resources/config/routing.yml"

    prefix:   /

refugee:
    resource: "@RefugeeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
