association_homepage:
    path:     /
    defaults: { _controller: AssociationBundle:Default:index }

add_categorie:
    path:     /addCategorie
    defaults: { _controller: AssociationBundle:Categorie:addCategorie }

update_categorie:
    path:     /updateCategorie/{id}
    defaults: { _controller: AssociationBundle:Categorie:updateCategorie }

get_all_categorie:
    path:     /getAllCategorie
    defaults: { _controller: AssociationBundle:Categorie:getAllCategorie }

delete_categorie:
    path:     /deleteCategorie/{id}
    defaults: { _controller: AssociationBundle:Categorie:deleteCategorie }

add_reclamation:
    path:     /addReclamation
    defaults: { _controller: AssociationBundle:Reclamation:addReclamation }

update_reclamation:
    path:     /updateReclamation
    defaults: { _controller: AssociationBundle:Reclamation:updateReclamation }

get_all_reclamations:
    path:     /getAllReclamations
    defaults: { _controller: AssociationBundle:Reclamation:getAllReclamations }

delete_reclamation:
    path:     /deleteReclamation
    defaults: { _controller: AssociationBundle:Reclamation:deleteReclamation }

add_association:
    path:     /addAssociation
    defaults: { _controller: AssociationBundle:Association:addAssociation }

update_association:
    path:     /updateAssociation/{id}
    defaults: { _controller: AssociationBundle:Association:updateAssociation }

get_all_association:
    path:     /getAllAssociation
    defaults: { _controller: AssociationBundle:Association:getAllAssociation }

get_association:
    path:     /getAssociation/{id}
    defaults: { _controller: AssociationBundle:Association:getAssociation }

delete_association:
    path:     /deleteAssociation{id}
    defaults: { _controller: AssociationBundle:Association:deleteAssociation }
