<?php

namespace RefugeeBundle\Repository;

/**
 * RefugeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefugeeRepository extends \Doctrine\ORM\EntityRepository
{
    public function countRef(){
        $query= $this->getEntityManager()->createQuery("Select count(v) as c , v.location  FROM RefugeeBundle:Refugee v
      group by v.location");


        return $query->getResult();
    }
    public function sumByNeeds(){
        $query= $this->getEntityManager()->createQuery("Select v.needs, SUM(v.value)  FROM RefugeeBundle:Refugee v
      group by  v.needs" );

        return $query->getResult();
    }
}
