donation_homepage:
    path:     /
    defaults: { _controller: DonationBundle:Default:index }

add:
    path:     /add
    defaults: { _controller: DonationBundle:Don:add }

get_don:
    path:     /getDon/{id}
    defaults: { _controller: DonationBundle:Don:getDon }

delete_don:
    path:     /deleteDon/{id}
    defaults: { _controller: DonationBundle:Don:deleteDon }

add_don:
    path:     /addDon/{id}
    defaults: { _controller: DonationBundle:Don:addDon }

update_don:
    path:     /updateDon/{id}
    defaults: { _controller: DonationBundle:Don:updateDon }

delete_dron:
    path:     /deleteDon/{id}
    defaults: { _controller: DonationBundle:Don:deleteDon }



get_all_don:
    path:     /getAllDon
    defaults: { _controller: DonationBundle:Don:getAllDon }

add_needs:
    path:     /addNeeds
    defaults: { _controller: DonationBundle:Needs:addNeeds }

delete_needs:
    path:     /deleteNeeds/{id}
    defaults: { _controller: DonationBundle:Needs:deleteNeeds }

update_needs:
    path:     /updateNeeds/{id}
    defaults: { _controller: DonationBundle:Needs:updateNeeds }

get_needs:
    path:     /getNeeds/{id}
    defaults: { _controller: DonationBundle:Needs:getNeeds }

get_all_needs:
    path:     /getAllNeeds
    defaults: { _controller: DonationBundle:Needs:getAllNeeds }

get_needs_value:
    path:     /getNeedsValue/{category}
    defaults: { _controller: DonationBundle:Needs:getNeedsValue }

get_don_value:
    path:     /getDonValue/{category}/{id}
    defaults: { _controller: DonationBundle:Don:getDonValue }

get_need:
    path:     /getNeed
    defaults: { _controller: DonationBundle:Needs:getNeed }
