services:
#    donation.example:
#        class: DonationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    donation.needs:
          class: DonationBundle\Controller\NeedsController
          arguments: []

