<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPnxpv0u\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPnxpv0u/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPnxpv0u.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPnxpv0u\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPnxpv0u\appDevDebugProjectContainer([
    'container.build_hash' => 'Pnxpv0u',
    'container.build_id' => '14b81c7b',
    'container.build_time' => 1594768571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPnxpv0u');
