<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7gghrnk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7gghrnk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7gghrnk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7gghrnk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7gghrnk\appDevDebugProjectContainer([
    'container.build_hash' => '7gghrnk',
    'container.build_id' => 'd1b1c433',
    'container.build_time' => 1595430150,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7gghrnk');
